### PR TITLE
Add to "## Basic functionality: Add tasks"

### PR DESCRIPTION
**Pull request by hines-sharrod**
As I was working through the tutorial I could not figure out why my list would not show up. I think it would be wise to make sure it is stated not to forget to set a height on the <ListView> component.

### CODE REVIEW

**Comment by rigor789** [comment]
Hey @ikoevska since you wrote this part, I thought I'd ping you to take a look!

**Comment by hines-sharrod** [comment]
Great, thank you. @ikoevska I just added those notes because my ListView component did not display for the To Do tab until I added a height. I randomly figured out that was the error, so I am sure more people are facing the same issue. Also, this was on iOS by the way.

**Comment by hines-sharrod** [comment]
If I am mistaken then there may be a bug because that is the only way it would show up.

**Comment by ikoevska** [comment]
@rigor789 thanks for pinging me! @hines-sharrod, the changes look good. 

I just tested it and you're right - the ListView no longer shows if you don't have height.  (At the time of writing this it worked without the property.) I'll note in the ListView docs as well.

**Comment by hines-sharrod** [comment]
@ikoevska Okay great, glad that I could catch that and help out.

**Comment by ikoevska** [comment]
I'll leave it to @rigor789 to confirm if it's OK but basically you can just go to the top where there's a contributors meta data field and add your github handle there :)

**Comment by ikoevska** [comment]
@rigor789 can you merge this as I'd like to work some more on the tutorial and I'd like to get the updated version. Thanks!

**Pull request merged**
