### PR TITLE
Rework layout docs

### PR DESCRIPTION
**Pull request by ikoevska**
WIP, reworking layout docs. @rigor789 can you supply/set up an image for the dock to center sample in DockLayout?

### CODE REVIEW

**Comment by rigor789** [comment]
@ikoevska can you sketch it out so I know what it needs to look like? (a freehand sketch or anything will work)

**Comment by rigor789** [comment]
@ikoevska Here you go: https://art.nativescript-vue.org/layouts/dock_layout_all_sides_and_stretch.svg

**Comment by ikoevska** [comment]
Finally done with this one. @rigor789 can you take a look? Basically, I've:
* reworded most of it
* added example descriptions everywhere

**Comment by rigor789** [comment]
@ikoevska looks good, thanks!

**Pull request merged**
