### PR TITLE
Added a Routing section

### LINKED ISSUE #40: Document usage of the Router
I'd be happy to take a stab at documenting usage of `vue-router`, but I'm not entirely sure where in the menu this should live. Suggestions?

### PR DESCRIPTION
**Pull request by EddyVerbruggen**
Closes #40

### CODE REVIEW

**Comment by rigor789** [comment]
Awesome! I'll merge this but I think we should cover component-routing as well. Basically page routing creates and navigates to new pages, and component-routing uses a single page, and replaces it's contents based on the active route.

**Comment by EddyVerbruggen** [comment]
Ah yes, that's also pretty useful. I'll open a new issue for that.

**Comment by Dibro89** [comment]
@EddyVerbruggen I'm new to ns and ns-vue and this doesn't work for me on iOS (using play.nativescript.org).
`ERROR: [Vue warn]: Error in directive view inserted hook: "Error: View already has a parent. View: ActionBar(##) Parent: Page(##)"`

**Comment by EddyVerbruggen** [comment]
@Dibro89 You forgot to add the code you're trying to run / the Playground link. And please go to the Slack #vue channel for quickest support.

**Comment by Dibro89** [comment]
@EddyVerbruggen Using the default ns-vue template and copy-pasted first routing example.
https://play.nativescript.org/?id=9S349j

I'll go to the Slack next time, thanks!

**Comment by EddyVerbruggen** [comment]
Looks like the sample no longer works indeed 🤔- you need to replace the Detail template with:

```html
    <Page>
      <ActionBar title="Detail"/>
      <StackLayout>
        <Button text="BACK" @tap="$navigateBack" />
      </StackLayout>
    </Page>
```

So the page actually has content.

**Comment by Dibro89** [comment]
@EddyVerbruggen It works, thank you!

**Pull request merged**
