### PR TITLE
Update the manual routing page

### PR DESCRIPTION
**Pull request by fartek**
Added info on how to pass properties to the created modal in the `$showModal` section.

### CODE REVIEW

**Comment by rigor789** [comment]
While that works, the more preferred approach is by passing props. It's almost the same, but the props themselves are better defined.

A simple example:

```js
// detail modal
export default {
  props: ['id']
}
```

and to pass the prop:

```js
this.$showModal(Detail, { context: { propsData: { id: 14 } }});
```

This is a more explicit way to go about it, and would be better to advise users this approach.

Let me know if you'd like to update the docs with the above information

**Comment by fartek** [comment]
@rigor789 
Ah, I was actually looking to find a way to use props but couldn't figure it out. This is much better! I'll update the docs with the 'propsData' method and I'll also update the $modal.close documentation as I don't see any mention of returning the data from the modal (which is done with promises if I'm correct).

**Comment by smakinson** [comment]
@rigor789 I apologize for asking a question here ( I have not yet received the slack invitation ). I hit what seems a bug ( all events seem to stop firing on Page with SegmentedBar/ListView, etc after using back button ) and I'm trying to see if its caused by using vue-router.  Can 

```
import View from './View'
this.$navigateTo(View, { context: { propsData: { videoId: 'theid' } }})
```

work where View is a .vue file? If so, what might the syntax look like? Or am I going to need to refactor a bit to try it with manual routing?

Thank you!

**Comment by flamoedo** [comment]
How to get the values sent on the forwarded page?

**Comment by thiagotiz** [comment]
@flamoedo   you can use to send "this.$navigateTo(Page, { props: { id: 234 }})"  and "props: ['id'],"  to get it.

**Pull request merged**
