### PR TITLE
Add Japanese translation for NativeScript-Vue docs

### PR DESCRIPTION
**Pull request by Spice-Z**
Hello.
Now,I'm translating documents to Japanese.
It's not fihish yet, this is Work In Progress.

I will leave WIP status when I translate all documents.

Thanks.

### CODE REVIEW

**Comment by rigor789** [comment]
@Spice-Z Wow! Awesome! Let me know when it's ready 👍

**Comment by Spice-Z** [comment]
Content of `getting-started/2-playground-tutorial.md` is too long to translate only by myself, 
so I want to release Japanese Document to recruit collabolator.

Other Japanese content maybe not perfect. I will continue to improve document.

**Comment by rigor789** [comment]
@Spice-Z Should I merge it then? Or you plan on collaborating inside your own repository? Either is fine with me, just let me know!

**Comment by Spice-Z** [comment]
@rigor789 Please merge it !  Thx!

**Pull request merged**
