### PR TITLE
🇪🇸Add Spanish translation for NativeScript-Vue docs

### PR DESCRIPTION
**Pull request by ianaya89**
This PR adds translations for the entire doc of NativeScript-Vue.

### CODE REVIEW

**Comment by rigor789** [comment]
Great job! We have recently updated the layout docs, so those may need to be updated, but this is awesome, thank you! :)

**Comment by ianaya89** [comment]
@rigor789 thanks. Not sure what has changed and what I need to update

**Comment by rigor789** [comment]
@ianaya89 here is the PR that changed the layout docs: https://github.com/nativescript-vue/nativescript-vue.org/pull/164

It has been restructured a little bit, with clearer descriptions of the examples. Heading levels also changed in a few places.

If you could incorporate these changes, that would be amazing!

**Comment by ianaya89** [comment]
@rigor789 Great, let me take a look to the changes and I will submit a PR soon.

BTW, I noticed that some default English text is placed in layouts/partials. I was thinking to add to those layouts/partials multilanguage support. Any ideas or suggestions?

**Comment by rigor789** [comment]
@ianaya89 Awesome! 

And yeah, there are a couple places with English, but there is no way currently to translate them. We may move the site to VuePress (https://vuepress.vuejs.org/) at some point, and then we can tackle that - but for now it's good as is, not a huge problem.

**Comment by ianaya89** [comment]
@rigor789 sounds good. Thank you!

**Pull request merged**
