### PR TITLE
Fixed: missing highlight of center property

### PR DESCRIPTION
**Pull request by suchorski**
I noted that are missing the highlight on documentation of center property in dock attribute

### CODE REVIEW

**Comment by rigor789** [comment]
Thanks for the PR, if I remember correctly, the reason it was not highlighted is because you cannot set `dock="center"` explicitly, instead it relies on `stretchLastChild` - in which case highlighting it could be confusing?

I'm open to thoughts however!

**Comment by suchorski** [comment]
> 
> 
> Thanks for the PR, if I remember correctly, the reason it was not highlighted is because you cannot set `dock="center"` explicitly, instead it relies on `stretchLastChild` - in which case highlighting it could be confusing?
> 
> I'm open to thoughts however!

I tested here and the behavior using `dock="center"` is different from `stretchLastChild`. I could dock a View in center and strech the bottom one.

**Comment by rigor789** [comment]
Oh you are 100% correct!

**Review by rigor789 — APPROVED** [review]

**Comment by suchorski** [comment]
> Oh you are 100% correct! 

I did not see, maybe this should be corrected to:

`To dock a child element to the center, it must be the last child of the container and you must set the stretchLastChild property of the parent to true.`

Will test and then pull again if necessary.

**Comment by rigor789** [comment]
Ok I did check, and indeed `center` isn't a valid dock value: 

https://github.com/NativeScript/NativeScript/blob/c3cadc7fd5c7afab37daf667227b4d55d7e07196/packages/core/core-types/index.d.ts#L341

**Comment by suchorski** [comment]
You are right. I tested and forget to see the source, sorry.

**Comment by rigor789** [comment]
I guess in this case, this change is not needed - but I appreciate your time for the PR 💯

**Pull request closed without merging**
